---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: asbest-os
description: Best OS ever

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
      - https://mise.jdx.dev/rpm/mise.repo
    install:
      # Development
      - automake
      - code
      - clang
      - gcc
      - lld
      - mise
      - mold
      - zed
      # Dependencies
      - ncurses-devel
      - openssl-devel
      # Media
      - kdenlive
      - ffmpeg
      - gimp
      - gwenview
      - okular
      - vlc
      # System
      - btop
      - fastfetch
      - kate
      - steam-devices
    remove:
      - nvtop
      - htop

  - type: signing
